export const GET_VALID_SEARCH_PHONE = "get_valid_search_phone";
export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const GET_CLIENTS = "get_clients";
export const GET_CLIENT = "GET_CLIENT";
export const GET_CLIENT_DATA = "GET_CLIENT_DATA";
export const GET_CLIENT_BY_ID_USER = "get_client_by_id_user";
export const GET_SELECTED_TRANSACTION = "get_selected_transaction";
export const GET_ARRAY_BY_NUMBER_PHONE = "GET_ARRAY_BY_NUMBER_PHONE";
export const GET_INPUT_SEARCH_NUMBER_PHONE_TEXT =
  "GET_INPUT_SEARCH_NUMBER_PHONE_TEXT";
export const IS_SING_IN = "IS_SING_IN";
export const IS_MODAL_CLIENT = "IS_MODAL_CLIENT";
export const detailInfoTransactionTest = "detailInfoTransactionTest";
export const setTestTransactions = "setTestTransactions";
export const GET_ARRAY_SORTED_BY_ID_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_ID_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_NAME_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_NAME_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_USERNAME_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_USERNAME_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_EMAIL_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_EMAIL_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_COMPANY_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_COMPANY_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_ADDRESS_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_ADDRESS_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_WEBSITE_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_WEBSITE_TRANSACTIONS";
export const GET_ARRAY_SORTED_BY_NUMBER_PHONE_TRANSACTIONS =
  "GET_ARRAY_SORTED_BY_NUMBER_PHONE_TRANSACTIONS";
